import type { SemanticGraphData } from '../src/graph/model.js';

export const GRAPH_FIXTURE = {
  schemaVersion: 1,
  nodes: [
    { id: 'doc:cdc', kind: 'document', label: 'CDC 2022 opioid guideline' },
    {
      id: 'entity:recommendation',
      kind: 'entity',
      label: 'Recommendation',
      document: 'cdc2022-opioid-rec05',
      sentence: 1,
    },
    {
      id: 'entity:dosage',
      kind: 'entity',
      label: 'Dosage reduction',
      document: 'cdc2022-opioid-rec05',
      sentence: 2,
    },
    {
      id: 'event:have',
      kind: 'event',
      label: 'have',
      document: 'cdc2022-opioid-rec05',
      sentence: 2,
    },
    {
      id: 'operator:should',
      kind: 'operator-context',
      label: 'should',
      document: 'cdc2022-opioid-rec05',
      sentence: 2,
    },
    { id: 'value:gradual', kind: 'value', label: 'gradual' },
    { id: 'doc:isolated', kind: 'document', label: 'Isolated document' },
  ],
  edges: [
    {
      id: 'edge:document-entity',
      kind: 'entity',
      source: 'doc:cdc',
      target: 'entity:recommendation',
      label: 'declares entity',
      document: 'cdc2022-opioid-rec05',
      sentence: 1,
      line: 10,
      predicate: 'guideline_entity',
    },
    {
      id: 'edge:recommendation-dosage',
      kind: 'implies',
      source: 'entity:recommendation',
      target: 'entity:dosage',
      label: 'implies',
      document: 'cdc2022-opioid-rec05',
      sentence: 2,
      line: 20,
      predicate: 'guideline_entity',
    },
    {
      id: 'edge:dosage-event',
      kind: 'event',
      source: 'entity:dosage',
      target: 'event:have',
      label: 'participates in event',
      document: 'cdc2022-opioid-rec05',
      sentence: 2,
      line: 21,
      predicate: 'guideline_event',
    },
    {
      id: 'edge:event-operator',
      kind: 'operator',
      source: 'event:have',
      target: 'operator:should',
      label: 'has operator context',
      document: 'cdc2022-opioid-rec05',
      sentence: 2,
      line: 22,
      predicate: 'guideline_operator',
    },
    {
      id: 'edge:event-value',
      kind: 'argument',
      source: 'event:have',
      target: 'value:gradual',
      label: 'argument 2',
      document: 'cdc2022-opioid-rec05',
      sentence: null,
      line: 23,
      predicate: 'guideline_arg',
    },
  ],
  stats: {
    documents: 2,
    clauses: 5,
    nodes: 7,
    edges: 5,
    byNodeKind: { document: 2, entity: 2, event: 1, 'operator-context': 1, value: 1 },
    byEdgeKind: { entity: 1, implies: 1, event: 1, operator: 1, argument: 1 },
  },
} as const satisfies SemanticGraphData;
