// The free-text intake vocabulary: which of the shipped rules a judgment may select, what
// triggers each, and the build-time goal that derives it. Generated by `tools/kb/intake.mjs`
// from the verified bag; this reader refuses any shape it was not written for, because a
// silently absorbed producer change would move which recommendation answers a user.

import generated from '@kb/intake-vocabulary.json';

import { isQuestionId, type QuestionId } from '../questions/catalog.js';

export type PainType = 'acute' | 'subacute' | 'chronic';

export type IntakeTrigger =
  { kind: 'condition'; condition: string } | { kind: 'section'; section: string };

export interface IntakeRule {
  id: string;
  document: string;
  sentence: number;
  trigger: IntakeTrigger;
  painSet: readonly PainType[];
  section: string;
  question: QuestionId;
  goal: string;
}

export interface IntakeVocabulary {
  vocabularyVersion: 1;
  digest: string;
  conditions: readonly { id: string; text: string }[];
  sections: readonly { id: string; heading: string; documents: readonly string[] }[];
  vocabulary: readonly string[];
  rules: readonly IntakeRule[];
}

const PAIN_TYPES: readonly string[] = ['acute', 'subacute', 'chronic'];
const GOAL = /^clinical_derive\('([a-z0-9-]+)',([1-9][0-9]*),Rule,Proof\)$/u;

const fail = (field: string, reason: string): never => {
  throw new Error(`intake vocabulary: ${field} ${reason} — run pnpm kb:build`);
};

const record = (value: unknown, field: string): Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : fail(field, 'is not an object');

const list = (value: unknown, field: string): readonly unknown[] =>
  Array.isArray(value) ? value : fail(field, 'is not an array');

const text = (value: unknown, field: string): string =>
  typeof value === 'string' && value !== '' ? value : fail(field, 'is not a non-empty string');

const keys = (value: Record<string, unknown>, expected: readonly string[], field: string): void => {
  const actual = Object.keys(value);
  if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) {
    fail(field, `has keys [${actual.join(', ')}], expected [${expected.join(', ')}]`);
  }
};

const unique = (ids: readonly string[], field: string): Set<string> => {
  const set = new Set(ids);
  if (set.size !== ids.length) fail(field, 'repeats an id');
  return set;
};

export const parseVocabulary = (raw: unknown): IntakeVocabulary => {
  const top = record(raw, 'artifact');
  keys(
    top,
    ['vocabularyVersion', 'digest', 'conditions', 'sections', 'vocabulary', 'rules'],
    'artifact',
  );
  if (top.vocabularyVersion !== 1)
    fail('vocabularyVersion', `${String(top.vocabularyVersion)} is not 1`);
  const digest = text(top.digest, 'digest');
  if (!/^[0-9a-f]{64}$/u.test(digest)) fail('digest', 'is not a sha256 hex digest');

  const conditions = list(top.conditions, 'conditions').map((entry, index) => {
    const item = record(entry, `conditions[${String(index)}]`);
    keys(item, ['id', 'text'], `conditions[${String(index)}]`);
    return Object.freeze({
      id: text(item.id, `conditions[${String(index)}].id`),
      text: text(item.text, `conditions[${String(index)}].text`),
    });
  });
  const sections = list(top.sections, 'sections').map((entry, index) => {
    const item = record(entry, `sections[${String(index)}]`);
    keys(item, ['id', 'heading', 'documents'], `sections[${String(index)}]`);
    const documents = list(item.documents, `sections[${String(index)}].documents`).map(
      (document, at) => text(document, `sections[${String(index)}].documents[${String(at)}]`),
    );
    if (documents.length === 0) fail(`sections[${String(index)}].documents`, 'is empty');
    return Object.freeze({
      id: text(item.id, `sections[${String(index)}].id`),
      heading: text(item.heading, `sections[${String(index)}].heading`),
      documents: Object.freeze(documents),
    });
  });
  const vocabulary = list(top.vocabulary, 'vocabulary').map((entry, index) =>
    text(entry, `vocabulary[${String(index)}]`),
  );
  const conditionIds = unique(
    conditions.map(({ id }) => id),
    'conditions',
  );
  const sectionIds = unique(
    sections.map(({ id }) => id),
    'sections',
  );

  const rules = list(top.rules, 'rules').map((entry, index): IntakeRule => {
    const field = `rules[${String(index)}]`;
    const item = record(entry, field);
    keys(
      item,
      ['id', 'document', 'sentence', 'trigger', 'painSet', 'section', 'question', 'goal'],
      field,
    );
    const document = text(item.document, `${field}.document`);
    const sentence = item.sentence;
    if (typeof sentence !== 'number' || !Number.isInteger(sentence) || sentence < 1) {
      fail(`${field}.sentence`, 'is not a positive integer');
    }
    const id = text(item.id, `${field}.id`);
    if (id !== `${document}:${String(sentence)}`)
      fail(`${field}.id`, 'is not <document>:<sentence>');
    const trigger = record(item.trigger, `${field}.trigger`);
    let parsedTrigger: IntakeTrigger;
    if (trigger.kind === 'condition') {
      keys(trigger, ['kind', 'condition'], `${field}.trigger`);
      const condition = text(trigger.condition, `${field}.trigger.condition`);
      if (!conditionIds.has(condition))
        fail(`${field}.trigger.condition`, `names unknown ${condition}`);
      parsedTrigger = Object.freeze({ kind: 'condition', condition });
    } else if (trigger.kind === 'section') {
      keys(trigger, ['kind', 'section'], `${field}.trigger`);
      const section = text(trigger.section, `${field}.trigger.section`);
      if (!sectionIds.has(section)) fail(`${field}.trigger.section`, `names unknown ${section}`);
      parsedTrigger = Object.freeze({ kind: 'section', section });
    } else {
      return fail(`${field}.trigger.kind`, 'is neither condition nor section');
    }
    const painSet = list(item.painSet, `${field}.painSet`).map((pain) =>
      typeof pain === 'string' && PAIN_TYPES.includes(pain)
        ? (pain as PainType)
        : fail(`${field}.painSet`, `holds ${String(pain)}`),
    );
    if (painSet.join() !== PAIN_TYPES.filter((pain) => painSet.includes(pain as PainType)).join()) {
      fail(`${field}.painSet`, 'is not ordered acute, subacute, chronic without repeats');
    }
    const section = text(item.section, `${field}.section`);
    const home = sections.find((candidate) => candidate.id === section);
    if (home === undefined || !home.documents.includes(document)) {
      fail(`${field}.section`, `does not hold ${document}`);
    }
    const question = item.question;
    if (!isQuestionId(question))
      return fail(`${field}.question`, `names unknown ${String(question)}`);
    const goal = text(item.goal, `${field}.goal`);
    const match = GOAL.exec(goal);
    if (match?.[1] !== document || match[2] !== String(sentence)) {
      fail(`${field}.goal`, `is not clinical_derive('${document}',${String(sentence)},Rule,Proof)`);
    }
    return Object.freeze({
      id,
      document,
      sentence: sentence as number,
      trigger: parsedTrigger,
      painSet: Object.freeze(painSet),
      section,
      question,
      goal,
    });
  });
  unique(
    rules.map(({ id }) => id),
    'rules',
  );
  if (conditions.length === 0 || sections.length === 0 || rules.length === 0) {
    fail('artifact', 'has an empty table');
  }

  return Object.freeze({
    vocabularyVersion: 1,
    digest,
    conditions: Object.freeze(conditions),
    sections: Object.freeze(sections),
    vocabulary: Object.freeze(vocabulary),
    rules: Object.freeze(rules),
  });
};

export const INTAKE_VOCABULARY: IntakeVocabulary = parseVocabulary(generated);
