// The service worker a build ships as `dist/sw.js`, generated from the built file list so the
// cache name changes whenever any hashed asset does. A changed KB input renames the PVM, which
// changes the name, so the new worker's `activate` deletes every cache holding the stale PVM.

import { createHash } from 'node:crypto';
import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

export const CACHE_PREFIX = 'cnl-ckc-';

/**
 * Hashed assets fetched only after a user action, cached when first fetched instead of on
 * install. The Japanese faces stay here so precaching never puts them on an English page.
 */
export const LAZY = [
  /^assets\/semantic-graph-/u,
  /^assets\/cytoscape/u,
  /^assets\/guideline-[^/]*\.pdf$/u,
  /^assets\/cdc\d+-opioid-/u,
  /^assets\/biz-udpgothic-/u,
  // The QLF fallback is insurance a sound image never takes (`tools/bundle.mjs`).
  /^assets\/swipl-bundle-/u,
  /^assets\/kb-[^/]+\.qlf$/u,
];

/** @param {string[]} files dist-relative paths @returns {{version: string, precache: string[]}} */
export const plan = (files) => ({
  version: createHash('sha256')
    .update([...files].sort().join('\n'))
    .digest('hex')
    .slice(0, 16),
  precache: files
    .filter((file) => file.startsWith('assets/') && !LAZY.some((lazy) => lazy.test(file)))
    .sort(),
});

/** @param {string[]} files @returns {string} */
export const serviceWorker = (files) => {
  const { version, precache } = plan(files);
  return `// Generated by tools/offline-sw.mjs.
const CACHE = ${JSON.stringify(CACHE_PREFIX + version)};
const PRECACHE = ${JSON.stringify(['./', ...precache.map((file) => `./${file}`)])};
const SHELL = new URL('./', self.registration.scope).href;
const ASSETS = new URL('./assets/', self.registration.scope).pathname;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith(${JSON.stringify(CACHE_PREFIX)}) && key !== CACHE)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== location.origin) return;
  // The shell goes to the network first, so a new deploy reaches an online visitor.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches.open(CACHE).then((cache) => cache.match(SHELL)).then((hit) => hit ?? Response.error()),
      ),
    );
    return;
  }
  if (!url.pathname.startsWith(ASSETS)) return;
  // Hashed names never change content, so a hit is always current.
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const hit = await cache.match(request);
      if (hit !== undefined) return hit;
      const response = await fetch(request);
      if (response.ok) await cache.put(request, response.clone());
      return response;
    }),
  );
});
`;
};

/** @param {string} dir @returns {string[]} every file under `dir`, relative to it */
const walk = (dir) =>
  readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)));

/** Writes `sw.js` into a finished build directory. @param {string} outDir */
export const writeServiceWorker = (outDir) => {
  const files = walk(outDir).filter((file) => file !== 'sw.js');
  writeFileSync(join(outDir, 'sw.js'), serviceWorker(files));
};
